#pragma once
// This code was generated by a vsSolutionBuildEvent.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#include "stdafx.h"

namespace net { namespace r_eg { namespace regXwild
{
    struct RXWVersion
    {
        struct TNum
        {
            const int major;
            const int minor;
            const int patch;
            const int build;

            TNum(int major, int minor, int patch, int build = 0)
                : major(major), minor(minor), patch(patch), build(build) { }

            TNum() : TNum(1, 2, 0, 0) { }

        } number;

        const TCHAR* bSha1      = _T("");
        const TCHAR* config     = _T("");
        const TCHAR* product    = _T("1.2.0");
    };
}}}
